version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:3000"

    environment:
      GN_CLIENT_ID: Client_Id_ff75193c46f8e08c01330c3f65f29a30e188690a
      GN_CLIENT_SECRET: Client_Secret_07022555af5dc9945a82a23ad90981d85110b196
      GN_CERTIFICATE_PATH: /usr/local/app/certs/homologacao-791074-Pix.p12
      GN_CERTIFICATE_PASS: ""
      GN_PIX_KEY: 57b24697-ffdf-49dd-a039-874f626ec0bc
      GN_SANDBOX: "true"
      GN_WEBHOOK_URL: "https://e37c527ef462.ngrok-free.app/api/webhook"

      FIREBASE_ACCOUNT_JSON:
        {
          "type": "service_account",
          "project_id": "teste-8fd60",
          "private_key_id": "2d5daedd6b8d91cae1d5b215cb4d2bcfc99cac1f",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFffsgqw6FRSR+\no7JI0EdHQtCeotv0tfqdkk6Q6g5NCVy/zcEw+f4RWHIPQGWkg1W75QR9qwQjibjz\nAmFFoUMpyHSHRnHSGUO4UaOdjNJwIJliTO2c+ksUBZtpLq4wZkuobDfIgXKm25Ho\n3CP98ALM+bvN7ezb0y8saVdhoy3HcVNGcA9pAtAjR3p0nUmw712GN/lhO+zOOrnK\nb0cjG4pk+Uj41yec9mEowk0q7dDuHeRsjU+LQhKdqUlxrpa6mgoE7DJJfAkqZBZ/\nbM6GgIw7TpKNiWv8QMvtwnSSj+yqfHyR7FQuCTwucflrUJOsKgNDWgcxiLe59YGl\no6UyBp3JAgMBAAECggEAYJONaXnNBYX85UMGzc2wdZwqadEpb/9H2aNw8TPMH4cL\nCK7FIT63LGNMj8HFktA47kP90Lh/MyPHwmpxB/xm3DlvJrHfukbpk2q08LgrNnLy\nnxwQfJn3egiN6b9OplN3/xpAozgOSaOJNE7m+OjUbclYOkl18T/SS00OUqxaGDOp\nvDkxQNEr106qYYkUzzL69Hy/trF52Mu+i5ek86R9CaGC9kSPf6B0mEJOD1ff+Bqs\ncLmpl28beZXj1Ef1VS+iEuYtWrr6Gv4+q8v12Iy8xx0xgSRl1EMmNTiFPUia5Vcq\nkkGwZMi0c2Na91nWL/+dEPRNH50AFa9VS8MLlYCyAwKBgQD0nGjZWthrKpiulcem\nH8R5WN2IzxPTTnPRnAVIodK+VLWExpSVnX52O22s0ECyEb18dw5WO2THl4qZMXSc\nYR2YcCX8L/iCCY2eoDV94LoJ4WiHj9fiX6ei/akkPR+/PLpmD2/XjOclgy/Ip9uR\nr6CY8aA0uZ0GH/ZmCP64Z4kvIwKBgQDOr/KhaqJRw8NQ1dcoalwr4HK9xTe9VSgn\nIJDFYqKisXrfxrsX7/rzBmvdVzCnmg1Nvla5bpikT6AkFgEROMOT6bEJkmdmWKBc\nZre4Inc9G/sN3CYtT3GCHJ0UExuj4K3yeRMPuQMeG+S1lqqhU4fQLy7rh/irI0sH\naOVcTC7kIwKBgQCjFnF1kXM/qEvaAvT01rNZMJ2rrF0Mgn8H3t1K+tGWosXPe9Lv\nGe2KCL9r/AFWeCt9A6fkaH8d7/SxhN65sKpZy1QYGye2E4Z/n1Nq1N1U3xuhXo9S\nV/Jd4n/WMIatK2Ef0OUBsukeAqRmRTxImu8ZaeglnyeJQOA4UYD7E9TMPwKBgEvH\nPpHn4rNPruCIRmZO+JQtqmPhVtpXymzuB6YWz8IOiBpbZmUUW1GW3R09xlzsokwK\nqQk7f0Ne3jvcxW9m/G3SlFIKF1byz3iRQHKGUGlbROSD/otGQTuO+hhOGSgwTBZG\nRbLSBk6Xs3bQUqbrVTQC2JUKOSWlvvBsiQsZ82c5AoGBAMIwjCOVMSNWvLjujNkW\nzOZK0dkCJrIfNLKCZHeG0GeRVKGBzPqndLCqW84Y3y8hiDCRKghoLVI3XMZOqU6Q\n2nkx74yfZYEtcc9a0F96nBaG23d43Oy5ij/VdqyczuQWNFLuDoswrS+UXXg9R9AK\ngH+3OgpVnHHeN1Co75JpBbiU\n-----END PRIVATE KEY-----\n",
          "client_email": "firebase-adminsdk-fbsvc@teste-8fd60.iam.gserviceaccount.com",
          "client_id": "109623712345280345057",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40teste-8fd60.iam.gserviceaccount.com",
          "universe_domain": "googleapis.com",
        }

      FIREBASE_ACCOUNT_PATH: /usr/local/app/firebase-service-account.json

      PORT: 3000
      NODE_ENV: development

    volumes:
      - .:/usr/local/app
      - /usr/local/app/node_modules
      - ./certs:/usr/local/app/certs
      - ./firebase-service-account.json:/usr/local/app/firebase-service-account.json
